### ISSUE TITLE
Roles will no longer work after the bot needs to relaunch

### ISSUE THREAD

**Issue by BarterClub** [ZeLarpMaster/ZeCogs#1]
Is there something i need to do if i restart computer or the red launcher?

**Comment by ZeLarpMaster** [comment]
You need to install my client_modification cog to fix that. Once you've installed it, just reload react_roles or reboot the bot.

**Comment by BarterClub** [comment]
sure is there a link to the cog

**Comment by BarterClub** [comment]
ok got it to work. Thanks

Might want to update red cog with the read.me to figure it out. Thanks for the help

**Comment by ZeLarpMaster** [comment]
Updated README.md to add a FAQ (4d89fe25da67c8fd3afc0a75b2ceb9a59c3e0141).

I included this question in there as the first frequently asked question (since I'm anticipating a lot to have that problem).

Thanks for the suggestion.
