### ISSUE TITLE
Link only one

### ISSUE THREAD

**Issue by dannymichel** [ZeLarpMaster/ZeCogs#12]
I have the react roles cog installed and have fun, slut, prude, and open minded roles linked. i want you to be able to react to slut, open minded, or fun roles and have all 3 of those, but not be able to have any one of those 3 if you have 'prude'. i tried linking prude  to each one of those individually, but that didnt work

**Comment by ZeLarpMaster** [comment]
The latest update should fix this. Please update and tell me if it works.

**Comment by ZeLarpMaster** [comment]
No response for 12 days, closing.

**Comment by chnaski** [comment]
It worked, yes, but I had to stop using this cog in favor of nadeko, as doing ``[p]top`` broke the cog if the person on the leaderboard left the server or deleted their account and there was no fix in site or issue addressed.

**Comment by ZeLarpMaster** [comment]
I have no idea what `[p]top` is, but ok.

Is the "fix in sight" about my cog? If so, I'd like some details since it could benefit other people as well.

**Comment by chnaski** [comment]
Ah apologies. That response was meant for the leveler cog.
Yours is working perfectly.

**Comment by ZeLarpMaster** [comment]
Alright, thanks for the feedback.
