### ISSUE TITLE
[react_roles] Role is only assigned after running check command

### ISSUE THREAD

**Issue by Kovaelin** [ZeLarpMaster/ZeCogs#17]
I've been using react roles, and it has been working well, but there is an older message (over three months old) that doesn't assign the role until I run the check command.

It also does not unassign the role when removing the reaction, even after running a check.

Possible bug?

**Comment by ZeLarpMaster** [comment]
`[p]roles check` does not remove roles. It only adds missing roles because removing roles is too expensive.

For your three months old problem, did you install client_modification? Does it work for all reactions you added when you restart the bot? Do you have any errors in the console?

**Comment by Kovaelin** [comment]
I installed client_modification first, before doing anything else, and it works when I test out on brand new messages. No errors. It's just that nothing happens until I use `[p]roles check`. It recognizes there's a role there when I use `[p]roles remove`.

**Comment by Kovaelin** [comment]
Latest V2. I've also noticed something very weird. When I remove reactions, the config file still remembers the server, channel, and message IDs. Even after I delete the entire config, it'll still come back the next I try to add something.

**Comment by ZeLarpMaster** [comment]
That's most likely because the config file creates a backup (config.bak)

Shutdown your bot, delete both files, and start it again. Then you'll have a fresh config.

I don't really know what your problem could be right now. Would you mind talking with me directly on Discord so I can join your server and take a look?

**Comment by Kovaelin** [comment]
So, I have a file that looks something like this:

>{
    "################" : {
        "################" : {
            "################" : {}
        },
        "################" : {
            "################" : {},
            "################" : {},
            "################" : {
                "###" : "################"
            }
        }
    }
}

**Comment by Kovaelin** [comment]
Okay, that got rid of the unwanted things in the config, but it just doesn't seem to work with anything that's older than messages that were created before the cog was installed. I tried one from a month ago and one from yesterday, but anything new works.

**Comment by ZeLarpMaster** [comment]
It not working for any message from before the cog was installed is a huge hint towards "client_modification" not being installed or not working. Did you ever restart the bot or reload the cog(s)?

**Comment by Kovaelin** [comment]
I did all those things. When a use `[p]cogs` it also shows that "client_modification" is loaded. I've shut down and restarted the bot and loaded and unloaded the cog. No error messages. Should it matter if the messages have been edited or not?

**Comment by ZeLarpMaster** [comment]
No, it doesn't matter whether the message was edited or not. The cog doesn't use the message's content for anything.

Can you try to remove both `react_roles` and `client_modification` and use `react_roles_bundled` instead? The config file is compatible between the two, so you shouldn't need to redo it.

When you do `[p]roles add` can you confirm the config file is modified accordingly?

**Comment by Kovaelin** [comment]
Same problem. Could any of my other cogs be causing conflicts? I'm also using an IRC-Discord relay. https://puu.sh/Aywdm.png

Config file is modified accordingly. Whether I add something old or something new, the config file looks good to me. I think I might leave it alone for now and try something else. Thanks again.

**Comment by Kovaelin** [comment]
Thanks a lot for your effort! Sorry for the trouble. I really appreciate it, though.

**Comment by ZeLarpMaster** [comment]
I looked through all of your cogs and I didn't see anything. I did not find `lib_calebj` and `highlight` though. It could be one of those two.

If you want to verify, you can try unloading both and restarting the bot. Then retry using react_roles.

If that still doesn't work, I don't think I can do much more to help you from here, unfortunately.

**Comment by Kovaelin** [comment]
It could be `lib_calebj`, but I am unable to unload that one.

**Comment by ZeLarpMaster** [comment]
If you run react_roles without client_modification, the cog will *not* work with any messages sent before the bot was online. This means it will break every single bound messages everytime you restart.

When you link one or multiple messages, you can only get one role out of all the roles available on the linked message(s). Linking 3 messages each with 1 role is exactly the same as linking 1 message with those 3 roles. For example: if roles A, B, and C are linked and user Alice has role A and B, if Alice clicks a reaction which gives her role C, Alice will lose role A and B while gaining role C.

You currently cannot link specific reactions/roles within a message without linking the other reactions/roles in that message. If you want to do that, I suggest splitting the reactions you want to be linked into different messages.

No, you cannot give "names" to messages.

**Comment by ZeLarpMaster** [comment]
I'll close this since I think it's solved.

Feel free to reopen or create a new issue referring to this one if you need further information or if you think this is still a problem (even though I've already stated I can't do much about it).
