### ISSUE TITLE
Role stacking

### ISSUE THREAD

**Issue by flazion** [ZeLarpMaster/ZeCogs#19]
Could you disable role-stacking, which is seen in this example: 
![rolestacking](https://user-images.githubusercontent.com/41591924/43293690-43709d30-9144-11e8-9896-0a215c0745d6.gif)
imagine clicking on one of three options, and don't allow them to select second unless he leaves his first selected role. 
I hope I made it clear? my english is not great so.. sorry.. :D

**Comment by ZeLarpMaster** [comment]
I made the react_roles cog which supports the feature you're asking for, but your gif is about the RoleReact bot which isn't made by me.

**Comment by flazion** [comment]
Oh, this gif is just an example of what I meant with role-stacking lol

**Comment by ZeLarpMaster** [comment]
Then what you want can already be achieved with `[p]help roles link`.

**Comment by flazion** [comment]
I tried linking, but still got role-stacked, or maybe I just don't understand it

**Comment by flazion** [comment]
I used [p]link <message_id> and received a message that it was linked, but when I selected two roles, they still both were applied.

**Comment by ZeLarpMaster** [comment]
`[p]link <message_id>` doesn't exist.

Use `[p]roles link <name> [<channel_id>-<message_id>...]` as specified in the help message of `[p]help roles link`

**Comment by flazion** [comment]
oh, my dumb ass..
when using [p]roles link <name> i always only specified channel_id even when clicking copy id, but after few tries of copying, it actually copied with the message_id like you specified  [<channel_id>-<message_id>...] this is why it always linked, but I still got role-stacked and now it works, sorry for the inconvenience.. :D

**Comment by ZeLarpMaster** [comment]
No problem.

Tip: As specified in the help message of that command, you can press shift while copying to copy both the channel id and the message id in the correct format.
