### ISSUE TITLE
Cannot use Non Standard Emoji

### ISSUE THREAD

**Issue by clovisd** [ZeLarpMaster/ZeCogs#2]
Hey!

I'm having trouble getting the bot to use custom server specific emoji's. The bot has "manage emojis" in server permissions and "add reaction emojis" permission on that specific channel and I keep getting the following message:
> :x: Emoji not found on the given channel's server or in unicode emojis.
> Or I may not have permissions to add reactions in the channel.

Any help would be greatly appreciated!

Thanks,
C

**Comment by ZeLarpMaster** [comment]
The bot doesn't need Manage Emojis, it only needs Manage Roles and Add Reaction Emojis.
The bot needs to see the emote in one of its servers to use the emote. It cannot use emotes from servers its not in.

Make sure your bot is in the server where your emote is from and make sure your bot has Add Reaction Emojis permission in the channel you give it, not in the channel where you run the command.

**Comment by clovisd** [comment]
The command I was using and message I was getting the bot to add the reaction to are the same Discord channel.

I was able to run the same command using one of the default standard emotes (I used :car:) with no trouble and it added the emote and would assign the role. However, when I try using a server-specific emote (specific to the server I was running the commands in), I get the message above. The bot also has full global permissions on the entire server as well as full channel permissions.

**Comment by ZeLarpMaster** [comment]
Did you use the emote's ID when running the command? Are you sure it was the right id?

**Comment by ZeLarpMaster** [comment]
Apparently the problem was the emote ID. They were doing a right click and Copy ID, but that copies the message's ID.

For future reference, if you want an emote's id, you can add a \ in front of it. The long number dispayed is the ID.
