### ISSUE TITLE
MessageProxy - Using Custom Emoji's / Different Server Emojis

### ISSUE THREAD

**Issue by clovisd** [ZeLarpMaster/ZeCogs#24]
Hey there!

I'm trying to use MessageProxy to post / edit messages and am trying to add / use custom emojis in the message, however they're not showing up in the message being "edited".

I've tried a couple things including using the `:emojiname:`, `<:emojiname:314101440731807744:>` and a variety of other emote ID combinations using the ID, Name, etc. Instead the emoji's are just being posted in plaintext.

Any help would be really appreciated! 

Thanks,
Clovis

**Comment by ZeLarpMaster** [comment]
When you're using MessageProxy, the bot is the one sending the messages. This means the bot needs to be in the server(s) which contain the custom emotes you want to use.

As as side note, MessageProxy performs absolutely no transformation to the sent text, it literally resends the raw message written.

One thing you can do is create a server with only you and your bot and add those emotes to that server. Make sure you use the right emotes when you do that by, for example, adding a prefix to the emotes when using them the first time.

**Comment by clovisd** [comment]
Hey there!

So even when the bot has access to the custom emotes (either directly on the server being posted or through a shared 3rd party mutual server), it doesn't post the custom emotes and just renders them in plain text.
![image](https://user-images.githubusercontent.com/1336589/51367494-1b846480-1aa8-11e9-8754-468bc2e788fe.png)
![image](https://user-images.githubusercontent.com/1336589/51367502-2c34da80-1aa8-11e9-9f91-99dbf9c92b65.png)

I can demonstrate if need be.

Thank you,
Clovis
