### ISSUE TITLE
how to setup the slowmode ... im kind of new to python and i really need this function in my server... 

### ISSUE THREAD

**Issue by kishorek437** [ZeLarpMaster/ZeCogs#25]

**Comment by kishorek437** [comment]
im trying to change the  parameters  but
not successful... i just want to make  like 
a user post one message in a channel per month... not able to send other message after sending one message

**Comment by ZeLarpMaster** [comment]
1. Install [Red-DiscordBot](https://twentysix26.github.io/Red-Docs/) if you haven't already
2. Install the [slowmode cog](https://cogs.red/cogs/ZeLarpMaster/ZeCogs/slowmode/) if you haven't already
3. Send `[p]slowmode #channel 2629746` where `[p]` is your bot's prefix and `#channel` is the channel on which you want to add this slowmode

If you can't follow those steps, please ask for help on the [cog support server](https://discord.gg/GET4DVk). The issues on this GitHub are for issues with my cogs, not with how to install them.

**Comment by kishorek437** [comment]
Thank you So much..... Its Working.......  the  DM  Feature is so cool......
