### ISSUE TITLE
mega broke help command with client modification

### ISSUE THREAD

**Issue by GGrandma** [ZeLarpMaster/ZeCogs#3]
I get this error when doing $help
`Exception in command 'help'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Unturned Succs\Desktop\PeaterBot\cogs\client_modification.py", line 113, in _default_help_command
    destination = ctx.message.author if bot.pm_help else ctx.message.channel
AttributeError: 'helpc' object has no attribute 'message'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "lib\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "lib\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'helpc' object has no attribute 'message'`

**Comment by ZeLarpMaster** [comment]
I'm not sure what could've caused this issue. Can you give some details about your bot?

Are you running v2? Do you have other cogs which might interfere with the help command?

**Comment by GGrandma** [comment]
sorry for the one month response time lol, i didnt do anything to produce this, all I do is install the cog and after that when i type [p]help the bot says a error occurred and the error that happend with the one shown in this issue. I have made sure the bot is up to date and have reinstalled the cog reloaded and restarted the bot and nothing works.

**Comment by ZeLarpMaster** [comment]
Does it work without the cog? Did you install the bot with a command like `pip install` or with `git clone`? (Is it v2 or v3 of RedBot)

Which cogs do you have installed? Can you try with only `client_modification` to see if it still breaks?

**Comment by GGrandma** [comment]
1. Yes everything works fine when the cog isn’t loaded, the second I load it the help command breaks. 2. I’m not 100% sure but I think I installed with git clone. 3. I have a lot of cogs installed... I have not tried having the cog alone. 

As you can see I have forked this and edited the client_modification.py to remove the [p]help_timout command and that fixed everything, the help command now works and react roles dosnt break even after restart. I really have no idea how what I did actully fixed it but it did, and i wasn’t planing on using [p]help_timeout anyways.

**Comment by ZeLarpMaster** [comment]
I've removed the help feature from `client_modification` to only keep the part which keeps `react_roles` working.

If you update it, you shouldn't have the problem anymore.

**Comment by GGrandma** [comment]
Thanks, sorry again for disappearing for a month lol, I had given up on trying to get it to work and I just decided that I wanted to try to get it working because it was a very useful cog.
