### ISSUE TITLE
No cogs available

### ISSUE THREAD

**Issue by hardlyneutral** [ZeLarpMaster/ZeCogs#31]
I've added your repo using:

`[p]repo add ZeCogs https://github.com/ZeLarpMaster/ZeCogs.git`

However, when attempting to list the cogs in your repo it shows none:

`[p]cog list ZeCogs`

![cog list](https://user-images.githubusercontent.com/4050857/69470088-e0069680-0d59-11ea-84ff-d73f51613f41.jpg)

**Comment by ZeLarpMaster** [comment]
That's not really an issue with this repo. You can ask for help on the [RedBot support server](https://discord.gg/GET4DVk) instead. I'm not really an expert at RedBot issues unlike people there.

**Comment by hardlyneutral** [comment]
Sounds good, I'll take my discussion there. Thanks!
