### ISSUE TITLE
Able to add repo but cant install any cogs.

### ISSUE THREAD

**Issue by mkono87** [ZeLarpMaster/ZeCogs#35]
When I go to install a cog, it says it cant find said cog. Does that for all. Is that because it doesnt support v3?

**Comment by ZeLarpMaster** [comment]
This repo is for V2. Go to https://github.com/ZeLarpMaster/ZeCogsV3 for my V3 cogs.

**Comment by TurnrDev** [comment]
Given how V3 is the default, might be an idea to name this V2
