### ISSUE TITLE
After a certain amount of time has passed, bot no longer places roles.

### ISSUE THREAD

**Issue by Overlordmittenz** [ZeLarpMaster/ZeCogs#4]
Task exception was never retrieved
future: <Task finished coro=<ReactRoles._init_bot_manipulation() done, defined at C:\Users\Administrator\Desktop\Red-DiscordBot\cogs\react_roles.py:88> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Red-DiscordBot\cogs\react_roles.py", line 95, in _init_bot_manipulation
    msg = await self.bot.get_message(channel, msg_id)
  File "lib\discord\client.py", line 1474, in get_message
    data = yield from self.http.get_message(channel.id, id)
AttributeError: 'NoneType' object has no attribute 'id'

I've installed client mod cog, as well as rebooted the bot and reloaded the cog. Still no dice after the time frame.

**Comment by ZeLarpMaster** [comment]
Please update the cog with the latest version. It might fix your problem.

**Comment by Overlordmittenz** [comment]
No luck. It seems that the cog times out after a certain period of time. Left 1 reaction up and checked it throughout the night. Stopped working sometime after I fell asleep.

**Comment by ZeLarpMaster** [comment]
Do you still have an error? The erroneous line in what you've sent doesn't exist anymore. I'd like to see what's the error now if you still have one.

**Comment by Overlordmittenz** [comment]
Not yet. It's been 24 hours and it's working as it should. Will update if anything changes.

**Comment by ZeLarpMaster** [comment]
Poking you to see if your issue was fixed. If it is, please tell me so I can close this issue.

**Comment by Overlordmittenz** [comment]
Yeah, sorry about the late response. After the fix and some changes on my servers end everything has been running smoothly since.
