### ISSUE TITLE
Missing permissions

### ISSUE THREAD

**Issue by GanjalfTheGreen** [ZeLarpMaster/ZeCogs#5]
Hey there & happy new Year,

I'm getting this error message on my Redbot when trying to add roles by emojis.

The bot actually edited the roles for some time but stopped at an unknown point for no reason.
So I tried to manually uptdate the Roles but it gave me this error. Command was
"!roles check MessageID Channel"

Since i'm kinda new to the whole business (linux and self hosting) I'd appreciate any kind of help!

Thanks alot!

![image](https://user-images.githubusercontent.com/28889034/34574062-9d00d036-f176-11e7-8b84-505336e60d66.png)

[04/01/2018 16:33] ERROR red on_command_error 369: Exception in command 'roles check'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/root/Red-DiscordBot/cogs/react_roles.py", line 365, in _roles_check
    await self.bot.add_roles(member, role)
  File "lib/discord/client.py", line 2915, in add_roles
    yield from self._replace_roles(member, new_roles)
  File "lib/discord/client.py", line 2886, in _replace_roles
    yield from self.http.replace_roles(member.id, member.server.id, roles)
  File "lib/discord/http.py", line 196, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: FORBIDDEN (status code: 403): Missing Permissions

**Comment by ZeLarpMaster** [comment]
The error you've sent happened when you ran `!roles check` and says the bot was missing permissions.
Make sure your bot has the permission to give all the bound roles. For example, if a role is above the bot's role, the bot can't give it.

If your bot stopped assigning roles, there was probably an error for it. Take a look for other errors in the logs.

**Comment by GanjalfTheGreen** [comment]
Thanks a lot, assigning the admin role to the bot fixed the problem, I'll keep an eye on it if he won't auto assign the roles.

Keep it up!
