### ISSUE TITLE
[Feature Request] [voice_gen] Allow more customization on the generators

### ISSUE THREAD

**Issue by GGrandma** [ZeLarpMaster/ZeCogs#7]
The one feature I want added is the option for voice channels to have their user limit set. Currently you can change permissions but not things like user limit.

Also I’m not sure about this but I don’t think you can change permissions on each channels generator, it seems that all channels have the same permissions.

**Comment by ZeLarpMaster** [comment]
Sounds like a good feature to add. I'll take a look when I can.

Please create a separate issue for the bug.

**Comment by PawanKolhe** [comment]
Yea. would love to have a user limit option. Really need it.

**Comment by ZeLarpMaster** [comment]
Permissions can now be changed per generator and you can now set the user limit per generator.

Update your cog to get the new features. The update breaks your existing generators. Just recreate them and it should be good.

If you have any new issues after the update, you can open a new issue.

**Comment by GGrandma** [comment]
Thanks so much, the update is great!

**Comment by PawanKolhe** [comment]
Thank you!
